name: CI

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            rust: beta
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            rust: stable
            target: aarch64-linux-android
          - os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
          - os: macOS-latest
            rust: stable
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        if: matrix.target != 'aarch64-linux-android'
        with:
          command: build
          args: --workspace --all-targets --target ${{ matrix.target }}
      - uses: actions-rs/cargo@v1
        if: matrix.target == 'aarch64-linux-android'
        env:
          TARGET_aarch64_linux_android_CC: ${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-clang
          TARGET_aarch64_linux_android_CXX: ${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-clang++
          TARGET_aarch64_linux_android_AR: ${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar
          RUSTFLAGS: -C linker=aarch64-linux-android-ld.gold
        with:
          command: build
          args: --target ${{ matrix.target }} --manifest-path openxr/Cargo.toml
      - uses: actions-rs/cargo@v1
        if: matrix.target != 'aarch64-linux-android'
        with:
          command: test
          args: --workspace

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install foreign dependencies
        run: sudo apt update && sudo apt-get -y install libxxf86vm-dev libxrandr-dev libgl1-mesa-dev
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        if: always()
        with:
          command: clippy
          args: --workspace --all-targets -- -D warnings
